{application,reverse_proxy_plug_websocket,
             [{modules,['Elixir.ReverseProxyPlugWebsocket',
                        'Elixir.ReverseProxyPlugWebsocket.Adapters.Gun',
                        'Elixir.ReverseProxyPlugWebsocket.Adapters.WebSockex',
                        'Elixir.ReverseProxyPlugWebsocket.Adapters.WebSockexClient',
                        'Elixir.ReverseProxyPlugWebsocket.Config',
                        'Elixir.ReverseProxyPlugWebsocket.ProxyProcess',
                        'Elixir.ReverseProxyPlugWebsocket.WebSocketClient',
                        'Elixir.ReverseProxyPlugWebsocket.WebSocketHandler']},
              {optional_applications,[gun,websockex]},
              {applications,[kernel,stdlib,elixir,logger,inets,ssl,plug,gun,
                             websockex,websock_adapter,websock]},
              {description,"Support reverse proxying of websocket connections natively in Elixir"},
              {registered,[]},
              {vsn,"0.2.0"}]}.
